
language: cpp



notifications:

  email: false



matrix:

  include:

    - os: linux

      compiler: g++-5

      env: COMPILER=g++ -std=c++11



script:

  - chmod 777 ./cpplint.py

  - ( for file in $(find ./lab1 -name "*.cpp"); do ./cpplint.py $file || exit; done );

  - ( for file in $(find ./lab2 -name "*.cpp"); do ./cpplint.py $file || exit; done );

  - ( for file in $(find ./lab3 -name "*.cpp"); do ./cpplint.py $file || exit; done );

  - cd lab1

  - mkdir build && cd build

  - cmake .. && make

  - cd ../..

  - cd lab2

  - mkdir build && cd build

  - cmake .. && make

  - cd ../..

  - cd lab3

  - mkdir build && cd build

  - cmake .. && make

#  - ./executable
